// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    
    {
      type: 'category',
      label: 'Models',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Quantify Heatwaves model',
          items: [
            'models/quantify-drivers/index',
            'models/quantify-drivers/usage',
            'models/quantify-drivers/data',            
          ],
        },
        {
          type: 'category',
          label: 'Forecast Heatwaves model',
          items: [
            'models/forecast-hw/index',
            'models/forecast-hw/usage',
            'models/forecast-hw/data',
          ],
        },
        {
          type: 'category',
          label: 'SEASgen',
          items: [
            'models/SEASgen/index',
            'models/SEASgen/usage',
            'models/SEASgen/data',
          ],
        },
      ],
    },
  ],
   
};

export default sidebars;
